apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-caiocunha
  namespace: caiocunha
spec:
  storageClassName: default-storage-class-caiocunha
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: caiocunha